rm(list=ls(all=TRUE))

x <- runif(10)
x <- sort(x)
y <- runif(10)
random <- cbind(x,y)
plot(random)
y.loess <- loess(y~x, span=.5, data.frame(x=x,y=y))
y.predict <- predict(y.loess, data.frame(x=x))
lines(x,y.predict)
lin <- lm(y~x)
abline(lin)

x <- runif(100)
x <- sort(x)
y <- runif(100)
random <- cbind(x,y)
plot(random)
y.loess <- loess(y~x, span=.5, data.frame(x=x,y=y))
y.predict <- predict(y.loess, data.frame(x=x))
lines(x,y.predict)
lin <- lm(y~x)
abline(lin)

x <- runif(1000)
x <- sort(x)
y <- runif(1000)
random <- cbind(x,y)
plot(random)
y.loess <- loess(y~x, span=.5, data.frame(x=x,y=y))
y.predict <- predict(y.loess, data.frame(x=x))
lines(x,y.predict)
lin <- lm(y~x)
abline(lin)

x <- runif(10000)
x <- sort(x)
y <- runif(10000)
random <- cbind(x,y)
plot(random)
y.loess <- loess(y~x, span=.5, data.frame(x=x,y=y))
y.predict <- predict(y.loess, data.frame(x=x))
lines(x,y.predict)
lin <- lm(y~x)
abline(lin)